server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: root
    password: 712459
    url: jdbc:mysql://localhost:3306/mall_inventory
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.google.com
    port: 587
    username: <changeit>
    password: <changeit>
    properties:
      mail:
        smtp:
          auth: true
          starrls:
            enable: true